# Generated by Django 4.0.1 on 2022-01-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('min_contribution_amount', models.IntegerField()),
                ('fund_address', models.CharField(max_length=255)),
                ('percent_fee', models.FloatField(default=0)),
                ('allow_topic_funds', models.BooleanField(default=False)),
                ('allow_choice_funds', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cycle_duration', models.DurationField()),
                ('topic_duration_in_cycles', models.IntegerField()),
                ('share_per_cycle_percentage', models.FloatField(default=0)),
                ('choice_min_support_threshold', models.FloatField(default=0)),
                ('choice_min_support_duration', models.DurationField()),
                ('prev_contributors_fee_percentage', models.FloatField(default=0)),
                ('topic_fund_address', models.CharField(blank=True, max_length=255, null=True)),
                ('topic_fund_fee_percentage', models.FloatField(default=0)),
                ('allow_choice_funds', models.BooleanField(default=False)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.arena')),
                ('tags', models.ManyToManyField(to='core.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TopicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('choice_fund_address', models.CharField(max_length=255)),
                ('fee_percentage', models.FloatField(default=0)),
                ('target_amount', models.IntegerField(default=10000000000)),
                ('conflicts_with', models.ManyToManyField(to='core.Choice')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ArenaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.arena')),
            ],
        ),
        migrations.AddField(
            model_name='arena',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.AddField(
            model_name='arena',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to='core.token'),
        ),
    ]
